version: '3.8'

services:
  app:
    build: .
    container_name: university_library_app
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/mydb
      NEXTAUTH_SECRET: changeme
      NEXTAUTH_URL: http://localhost:3000
      NEXT_PUBLIC_IMAGEKIT_PUBLIC_KEY: your-public-key
      IMAGEKIT_PRIVATE_KEY: your-private-key
      IMAGEKIT_URL_ENDPOINT: https://ik.imagekit.io/your_id
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: university_library_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
